### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by BeigeRonin** [gormanb/homebridge-hivehome-control#1]
**Describe Your Problem:**

The install fails with: "Operation failed with code 1.
You can download this log file for future reference.
See https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting for help."

**Logs:**

```
USER: namehere
DIR: /usr/local
CMD: npm install -g homebridge-hivehome-control@1.0.1
[?25l
[..................] | idealTree:lib: sill idealTree buildDeps
[..................] | idealTree:lib: sill idealTree buildDeps
[..................] | idealTree:lib: sill idealTree buildDeps
[..................] | idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] / idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] \ idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] \ idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] \ idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] / idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] / idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] / idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] \ idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] | idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] \ idealTree:lib: timing idealTree:#root Completed in 908ms
[#########.........] - idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] - idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] \ idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] | idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] | idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] | idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] | idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] | idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] | idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] \ idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] \ idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] \ idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] | idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] | idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] | idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] | idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] | idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] | idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] | idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] | idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] | idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] | idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] - idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] - idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] - idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] - idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] \ idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] \ idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] \ idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] \ idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] | idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] | idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] - idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] | idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] | idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] | idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] \ idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] \ idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] \ idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] / idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] - idealTree:make-dir: sill fetch manifest glob@^7.1.3
[#########.........] \ idealTree:make-dir: timing idealTree:node_modules/homebridge-hi
[#########.........] - idealTree:make-dir: timing idealTree:node_modules/homebridge-hi
[#########.........] \ idealTree:make-dir: timing idealTree:node_modules/homebridge-hi
[#########.........] / idealTree:make-dir: timing idealTree:node_modules/homebridge-hi
[#########.........] | idealTree:make-dir: timing idealTree:node_modules/homebridge-hi
[#########.........] / idealTree:make-dir: timing idealTree:node_modules/homebridge-hi
[#########.........] / idealTree:make-dir: timing idealTree:node_modules/homebridge-hi
[#########.........] - idealTree:make-dir: timing idealTree:node_modules/homebridge-hi
[#########.........] \ idealTree:make-dir: timing idealTree:node_modules/homebridge-hi
[#########.........] - idealTree:make-dir: timing idealTree:node_modules/homebridge-hi
[#########.........] - idealTree: timing idealTree Completed in 8106ms
[#########.........] | reify:enquirer: timing reify:loadBundles Completed in 0ms
[#########.........] | reify:enquirer: timing reify:loadBundles Completed in 0ms
[###########.......] | reify:homebridge-hivehome-control: timing reifyNode:node_module
[############......] - reify:color-support: http fetch GET 200 https://registry.npmjs.
[##############....] | reify:whatwg-url: timing reifyNode:node_modules/homebridge-hive
[###############...] - reify:commander: timing reifyNode:node_modules/homebridge-hiveh
[################..] | reify:semver: timing reifyNode:node_modules/homebridge-hivehome
[#################.] / reify:readable-stream: http fetch GET 200 https://registry.npmj
[#################.] - reify:@octokit/openapi-types: timing reifyNode:node_modules/hom
[#################.] - reify:@octokit/request: http fetch GET 200 https://registry.npm
[#################.] - reify:@octokit/request: http fetch GET 200 https://registry.npm
[#################.] - reify:@octokit/request: http fetch GET 200 https://registry.npm
[#################.] - reify:@octokit/request: http fetch GET 200 https://registry.npm
[#################.] - reify:@octokit/request: http fetch GET 200 https://registry.npm
[#################.] - reify:@octokit/request: http fetch GET 200 https://registry.npm
[#################.] - reify:@octokit/request: http fetch GET 200 https://registry.npm
[#################.] - reify:@octokit/request: http fetch GET 200 https://registry.npm
[#################.] - reify:@octokit/request: http fetch GET 200 https://registry.npm
[#################.] | reify:@octokit/request: http fetch GET 200 https://registry.npm
[##################] | reify:@octokit/plugin-paginate-rest: http fetch GET 200 https:/
[##################] | reify:@octokit/plugin-paginate-rest: http fetch GET 200 https:/

> pymport@1.4.3 install
> node-pre-gyp install --fallback-to-build && node scripts/patch-prefix.js
[##################] / reify:@octokit/plugin-retry: timing reifyNode:node_modules/home
[##################] / reify:@octokit/plugin-retry: timing reifyNode:node_modules/home
[##################] / reify:@octokit/plugin-retry: timing reifyNode:node_modules/home
[##################] / reify:@octokit/plugin-retry: timing reifyNode:node_modules/home
[##################] / reify:@octokit/plugin-retry: timing reifyNode:node_modules/home
[##################] / reify:@octokit/plugin-retry: timing reifyNode:node_modules/home
[##################] / reify:@octokit/plugin-retry: timing reifyNode:node_modules/home
[##################] / reify:@octokit/plugin-retry: timing reifyNode:node_modules/home
[##################] / reify:@octokit/plugin-retry: timing reifyNode:node_modules/home
[##################] / reify:@octokit/plugin-retry: timing reifyNode:node_modules/home
node-pre-gyp
 ERR! install response status 404 Not Found on https://github.com/mmomtchev/pymport/releases/download/v1.4.3/darwin-arm64.tar.gz
[##################] / reify:@octokit/plugin-retry: timing reifyNode:node_modules/home
[##################] / reify:@octokit/plugin-retry: timing reifyNode:node_modules/home
[##################] / reify:@octokit/plugin-retry: timing reifyNode:node_modules/home
[##################] / reify:@octokit/plugin-retry: timing reifyNode:node_modules/home
[##################] / reify:@octokit/plugin-retry: timing reifyNode:node_modules/home
[##################] / reify:@octokit/plugin-retry: timing reifyNode:node_modules/home
[##################] / reify:@octokit/plugin-retry: timing reifyNode:node_modules/home
[##################] / reify:@octokit/plugin-retry: timing reifyNode:node_modules/home
[##################] / reify:@octokit/plugin-retry: timing reifyNode:node_modules/home
/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config --cflags python3-embed' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
[##################] / reify:@octokit/plugin-retry: timing reifyNode:node_modules/home
gyp
 ERR! configure error
gyp ERR!
 stack Error: `gyp` failed with exit code: 1
gyp
ERR!
 stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:325:16)
gyp ERR!
 stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR!
 System Darwin 23.2.0
gyp
ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/homebridge-hivehome-control/node_modules/pymport/lib/binding/darwin-arm64/pymport.node" "--module_name=pymport" "--module_path=/usr/local/lib/node_modules/homebridge-hivehome-control/node_modules/pymport/lib/binding/darwin-arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
gyp ERR!
 cwd /usr/local/lib/node_modules/homebridge-hivehome-control/node_modules/pymport
gyp ERR! node -v v18.16.1
gyp ERR! node-gyp -v
 v9.3.1
gyp ERR! not ok
node-pre-gyp
 ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/homebridge-hivehome-control/node_modules/pymport/lib/binding/darwin-arm64/pymport.node --module_name=pymport --module_path=/usr/local/lib/node_modules/homebridge-hivehome-control/node_modules/pymport/lib/binding/darwin-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
node-pre-gyp
 ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-hivehome-control/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Darwin 23.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/homebridge-hivehome-control/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR!
cwd /usr/local/lib/node_modules/homebridge-hivehome-control/node_modules/pymport
node-pre-gyp
ERR! node -v v18.16.1
node-pre-gyp
ERR! node-pre-gyp -v v1.0.11
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/homebridge-hivehome-control/node_modules/pymport/lib/binding/darwin-arm64/pymport.node --module_name=pymport --module_path=/usr/local/lib/node_modules/homebridge-hivehome-control/node_modules/pymport/lib/binding/darwin-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
[##################] - reify:@octokit/plugin-retry: timing reifyNode:node_modules/home

[?25h
npm ERR!
 code 1
npm ERR!
 path /usr/local/lib/node_modules/homebridge-hivehome-control/node_modules/pymport
npm
ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build && node scripts/patch-prefix.js
npm ERR! A complete log of this run can be found in:
npm
 ERR!
     /Users/neilwillmott/.npm/_logs/2024-02-07T10_04_30_735Z-debug-0.log


Operation failed with code 1.

You can download this log file for future reference.

See https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting for help.

```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by gormanb** [comment]
Hi @BeigeRonin - thanks for raising this issue. Am I right that you are attempting to install the plugin on an M1 Mac? The plugin uses a bridge layer to interface with a Python library, and this bridge layer is not currently compatible with Apple Silicon.

I've just published a beta version, `1.0.2-beta.0`, which uses a different bridge layer that should be compatible with M1s. Could you try installing that version and see if it resolves the problem? Note that this version of the plugin requires `python3` and `pip3` to be installed on your system, but they likely already are.

**Comment by BeigeRonin** [comment]
Hi

The beta version work perfectly first time! Everything’s running fine in HB :)

Thanks

Neil

**Comment by gormanb** [comment]
Glad to hear it @BeigeRonin! I'll promote this beta to a full release version shortly.
